---
- name: Disable SQM
  notify: Reload sqm
  community.openwrt.uci:
    command: delete
    key: "sqm.ansible_wan"
    autocommit: true
  ignore_errors: true

- name: Enable hardware flow offloading
  notify: Restart firewall
  community.openwrt.uci:
    command: set
    key: "firewall.@defaults[0].{{ item }}"
    value: '1'
    autocommit: true
  loop:
    - flow_offloading
    - flow_offloading_hw
