---
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 2283
  selector:
    app: immich

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: default
  annotations:
    homer.service.name: Media
    homer.item.name: immich
    homer.item.logo: "https://immich.app/img/immich-logo-stacked-dark.svg"
spec:
  tls:
    - hosts:
        - immich.{{ .Values.fqdn }}
      secretName: {{ .Values.fqdn }}-tls
  rules:
    - host: immich.{{ .Values.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich
                port:
                  name: web

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-env
  namespace: default
data:
  IMMICH_PORT: "2283"
  REDIS_HOSTNAME: "redis-master"
  REDIS_PORT: "6379"
  DB_HOSTNAME: "postgresql"
  DB_PORT: "5432"
  DB_DATABASE_NAME: "immich"
  DB_USERNAME: "postgres"
  DB_VECTOR_EXTENSION: "pgvector"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: default
  labels:
    app: immich
  annotations:
    reloader.stakater.com/auto: "true"
    keel.sh/policy: force
    keel.sh/matchTag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@daily"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      nodeSelector:
        # Schedule only on NAS nodes
        nas: "true"
      containers:
        - name: app
          image: ghcr.io/immich-app/immich-server:v1.128.0
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 2000m
          envFrom:
            - configMapRef:
                name: immich-env
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.postgresql.credentials.postgresql.acid.zalan.do
                  key: password
            - name: IMMICH_WORKERS_INCLUDE
              value: "api"
          ports:
            - name: web
              containerPort: 2283
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
        - name: jobs
          image: ghcr.io/immich-app/immich-server:v1.128.0
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 2000m
              gpu.intel.com/i915: 1
          envFrom:
            - configMapRef:
                name: immich-env
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.postgresql.credentials.postgresql.acid.zalan.do
                  key: password
            - name: IMMICH_WORKERS_EXCLUDE
              value: "api"
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
      volumes:
        - name: data
          hostPath:
            path: /storage/immich/data

---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 3003
  selector:
    app: immich-machine-learning

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: default
  labels:
    app: immich-machine-learning
  annotations:
    keel.sh/policy: force
    keel.sh/matchTag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@daily"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: app
          image: ghcr.io/immich-app/immich-machine-learning:v1.128.0
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 2000m
          env:
            - name: IMMICH_PORT
              value: "3003"
          ports:
            - name: web
              containerPort: 3003
          volumeMounts:
            - name: cache
              mountPath: /cache
              subPath: cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: immich-machine-learning
