# code: language=ansible
---
- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart headscale
  ansible.builtin.service:
    name: headscale
    enabled: true
    state: restarted

- name: Reload sqm
  ansible.builtin.service:
    name: sqm
    state: reloaded

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Reload network
  ansible.builtin.service:
    name: network
    state: reloaded

- name: Reload firewall
  ansible.builtin.service:
    name: firewall
    state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
